import { combo, effect, num, toggle } from '@hypercolor/sdk'
import shader from './fragment.glsl'

export default effect(
    'Voidweaver',
    shader,
    {
        // ── Color ────────────────────────────────────────────────
        palette: combo(
            'Palette',
            [
                'Sapphire',
                'Cyberpunk',
                'Inferno',
                'Toxic',
                'Ethereal',
                'Monochrome',
                'Spectrum',
                'Electric',
                'Amethyst',
                'Coral',
                'Abyss',
                'Emerald',
                'Neon',
                'Rose Gold',
                'Sunset',
                'Vaporwave',
            ],
            {
                default: 'Sapphire',
                tooltip: 'Color scheme — 16 palettes from deep ocean to neon fire.',
                group: 'Color',
            },
        ),
        intensity: num('Intensity', [0, 100], 50, {
            step: 1,
            tooltip: 'Color brightness — crank past 50 for overdriven vibrancy.',
            group: 'Color',
        }),
        saturation: num('Saturation', [0, 100], 50, {
            step: 1,
            tooltip: 'Color richness — low for ghostly wash, high for neon punch.',
            group: 'Color',
        }),
        colorShift: toggle('Color Shift', true, {
            tooltip: 'Adds spatial color variation along the tunnel walls.',
            group: 'Color',
        }),
        colorCycle: num('Color Cycle', [0, 100], 50, {
            step: 1,
            tooltip: 'How fast the palette morphs — 0 freezes color, 100 is hyperdrive.',
            group: 'Color',
        }),
        pulse: num('Pulse', [0, 100], 0, {
            step: 1,
            tooltip: 'Rhythmic color breathing — multi-frequency intensity waves.',
            group: 'Color',
        }),

        // ── Motion ───────────────────────────────────────────────
        speed: num('Speed', [1, 10], 5, {
            step: 0.5,
            tooltip: 'Tunnel flight speed — how fast you fall into the void.',
            group: 'Motion',
        }),
        reverse: toggle('Reverse', false, {
            tooltip: 'Flip tunnel direction — ascend instead of descend.',
            group: 'Motion',
        }),
        wave: num('Wave', [0, 100], 0, {
            step: 1,
            tooltip: 'Motion distortion — organic wave ripples along the tunnel path.',
            group: 'Motion',
        }),

        // ── Tunnel ───────────────────────────────────────────────
        width: num('Width', [0, 100], 50, {
            step: 1,
            tooltip: 'Claustrophobic tight (0) to vast cavernous (100).',
            group: 'Tunnel',
        }),
        texture: num('Surface', [0, 100], 50, {
            step: 1,
            tooltip: 'Smooth glass walls (0) to organic alien flesh (100).',
            group: 'Tunnel',
        }),
        fog: num('Fog', [0, 100], 50, {
            step: 1,
            tooltip: 'Crystal clear (0) to thick atmospheric haze (100).',
            group: 'Tunnel',
        }),

        // ── Camera ───────────────────────────────────────────────
        fov: num('FOV', [0, 100], 50, {
            step: 1,
            tooltip: 'Telephoto warp speed (0) to fisheye trippy (100).',
            group: 'Camera',
        }),
        tilt: num('Tilt', [0, 100], 50, {
            step: 1,
            tooltip: 'Camera sway amount — 0 is locked, 100 is seasick.',
            group: 'Camera',
        }),

        // ── Style ────────────────────────────────────────────────
        style: combo('Style', ['Standard', 'Chromatic Shift', 'Phosphor'], {
            default: 'Standard',
            tooltip: 'Visual post-processing — clean, light-splitting aberration, or retro CRT phosphor.',
            group: 'Style',
        }),
    },
    {
        description:
            'Raymarched infinite tunnel. Sixteen palettes, five visual styles, camera physics, surface detail. A void that pulls you in.',
        presets: [
            {
                name: 'Infinite Descent',
                description:
                    'The classic. Sapphire walls rush past as you freefall through an endless geometric abyss, just enough fog to feel the depth.',
                controls: {
                    colorCycle: 40,
                    colorShift: true,
                    fog: 55,
                    fov: 50,
                    intensity: 55,
                    palette: 'Sapphire',
                    pulse: 0,
                    reverse: false,
                    saturation: 60,
                    speed: 5,
                    style: 'Standard',
                    texture: 50,
                    tilt: 30,
                    wave: 0,
                    width: 50,
                },
            },
            {
                name: 'Neon Gauntlet',
                description:
                    'Tight corridor at breakneck speed. Neon walls split into prismatic streaks as you thread through a digital obstacle course of pure light.',
                controls: {
                    colorCycle: 70,
                    colorShift: true,
                    fog: 20,
                    fov: 65,
                    intensity: 70,
                    palette: 'Neon',
                    pulse: 40,
                    reverse: false,
                    saturation: 75,
                    speed: 8,
                    style: 'Chromatic Shift',
                    texture: 30,
                    tilt: 20,
                    wave: 10,
                    width: 25,
                },
            },
            {
                name: 'Hellmouth',
                description:
                    'Reversed through a molten throat. Fire licks the rough organic walls as you ascend from the depths of something alive and burning.',
                controls: {
                    colorCycle: 30,
                    colorShift: true,
                    fog: 40,
                    fov: 60,
                    intensity: 75,
                    palette: 'Inferno',
                    pulse: 30,
                    reverse: true,
                    saturation: 80,
                    speed: 6,
                    style: 'Standard',
                    texture: 80,
                    tilt: 35,
                    wave: 20,
                    width: 30,
                },
            },
            {
                name: 'Ghost Ship',
                description:
                    'Spectral drift through impossible fog. Ethereal pastels phase through phosphor glow as the tunnel breathes around you.',
                controls: {
                    colorCycle: 60,
                    colorShift: true,
                    fog: 85,
                    fov: 40,
                    intensity: 40,
                    palette: 'Ethereal',
                    pulse: 25,
                    reverse: false,
                    saturation: 45,
                    speed: 3,
                    style: 'Phosphor',
                    texture: 20,
                    tilt: 45,
                    wave: 15,
                    width: 75,
                },
            },
            {
                name: 'Toxic Drain',
                description:
                    'Industrial runoff channel. Acid green walls pulse with chemical light as wave distortion warps the geometry into something alive.',
                controls: {
                    colorCycle: 45,
                    colorShift: false,
                    fog: 50,
                    fov: 50,
                    intensity: 65,
                    palette: 'Toxic',
                    pulse: 20,
                    reverse: false,
                    saturation: 70,
                    speed: 5,
                    style: 'Standard',
                    texture: 60,
                    tilt: 15,
                    wave: 30,
                    width: 40,
                },
            },
            {
                name: 'Midnight Express',
                description:
                    'Silver and shadow at dangerous speed. Monochrome light fractures through chromatic edges as you hurtle through liquid mercury.',
                controls: {
                    colorCycle: 10,
                    colorShift: false,
                    fog: 60,
                    fov: 55,
                    intensity: 50,
                    palette: 'Monochrome',
                    pulse: 0,
                    reverse: false,
                    saturation: 20,
                    speed: 7,
                    style: 'Chromatic Shift',
                    texture: 45,
                    tilt: 40,
                    wave: 0,
                    width: 35,
                },
            },
            {
                name: 'Crystal Cavern',
                description:
                    'Slow drift through an amethyst geode. Rough crystalline surfaces catch purple light as you glide through a gem the size of a cathedral.',
                controls: {
                    colorCycle: 25,
                    colorShift: true,
                    fog: 25,
                    fov: 45,
                    intensity: 60,
                    palette: 'Amethyst',
                    pulse: 15,
                    reverse: false,
                    saturation: 65,
                    speed: 3,
                    style: 'Standard',
                    texture: 75,
                    tilt: 25,
                    wave: 10,
                    width: 70,
                },
            },
            {
                name: 'Electric Storm',
                description:
                    'Lightning cracks through a pulsing vortex. The tunnel writhes with wave distortion as electric blue and white flash in violent rhythm.',
                controls: {
                    colorCycle: 80,
                    colorShift: true,
                    fog: 35,
                    fov: 55,
                    intensity: 70,
                    palette: 'Electric',
                    pulse: 65,
                    reverse: false,
                    saturation: 65,
                    speed: 8,
                    style: 'Standard',
                    texture: 40,
                    tilt: 55,
                    wave: 50,
                    width: 45,
                },
            },
            {
                name: 'Coral Depths',
                description:
                    'Sinking through a living reef. Warm coral hues drift through heavy underwater fog, the walls textured like ancient ocean stone.',
                controls: {
                    colorCycle: 35,
                    colorShift: true,
                    fog: 75,
                    fov: 40,
                    intensity: 55,
                    palette: 'Coral',
                    pulse: 10,
                    reverse: false,
                    saturation: 60,
                    speed: 3,
                    style: 'Standard',
                    texture: 55,
                    tilt: 30,
                    wave: 25,
                    width: 65,
                },
            },
            {
                name: 'Vapor Trail',
                description:
                    'Retro 80s aesthetic in tunnel form. Pink and cyan vaporwave hues drift lazily through a wide passage with gentle camera sway.',
                controls: {
                    colorCycle: 50,
                    colorShift: true,
                    fog: 55,
                    fov: 50,
                    intensity: 50,
                    palette: 'Vaporwave',
                    pulse: 20,
                    reverse: false,
                    saturation: 55,
                    speed: 4,
                    style: 'Standard',
                    texture: 30,
                    tilt: 50,
                    wave: 5,
                    width: 60,
                },
            },
            {
                name: 'Spectrum Warp',
                description:
                    'Every color at once at warp speed. Rainbow light refracts off tight walls as the tunnel twists and writhes with maximum wave distortion.',
                controls: {
                    colorCycle: 90,
                    colorShift: true,
                    fog: 30,
                    fov: 70,
                    intensity: 65,
                    palette: 'Spectrum',
                    pulse: 50,
                    reverse: false,
                    saturation: 75,
                    speed: 7,
                    style: 'Standard',
                    texture: 50,
                    tilt: 45,
                    wave: 40,
                    width: 30,
                },
            },
            {
                name: 'Abyssal Trench',
                description:
                    'The deepest dark. Bioluminescent sparks pierce through maximum fog as you crawl through a vast underwater chasm at the edge of vision.',
                controls: {
                    colorCycle: 20,
                    colorShift: true,
                    fog: 90,
                    fov: 35,
                    intensity: 35,
                    palette: 'Abyss',
                    pulse: 15,
                    reverse: false,
                    saturation: 50,
                    speed: 2,
                    style: 'Standard',
                    texture: 60,
                    tilt: 20,
                    wave: 20,
                    width: 80,
                },
            },
        ],
    },
)
