//! Discovery orchestrator for parallel driver-source coordination and deduplication.
//!
//! The [`DiscoveryOrchestrator`] runs all registered driver discovery sources
//! concurrently, deduplicates their results, diffs against the device
//! registry, and reports what changed.

use std::collections::{HashMap, HashSet};
use std::future::Future;
use std::pin::Pin;
use std::time::{Duration, Instant};

use anyhow::Result;
use hypercolor_driver_api::DiscoveredDevice;
use tokio::task::JoinSet;
use tracing::{info, warn};

use hypercolor_types::device::{DeviceFingerprint, DeviceId};

use super::registry::DeviceRegistry;

// ── DiscoveryReport ──────────────────────────────────────────────────────

/// Report generated by a full discovery sweep.
///
/// Summarizes what changed compared to the previous known device set.
#[derive(Debug)]
pub struct DiscoveryReport {
    /// Devices seen for the first time.
    pub new_devices: Vec<DeviceId>,

    /// Previously known devices that reappeared.
    pub reappeared_devices: Vec<DeviceId>,

    /// Previously known devices missing from this scan.
    pub vanished_devices: Vec<DeviceId>,

    /// Per-scanner timing and outcome diagnostics.
    pub scanner_reports: Vec<ScannerScanReport>,

    /// Total devices in the registry after this scan.
    pub total_known: usize,

    /// How long the full scan took.
    pub scan_duration: std::time::Duration,
}

/// One scanner's outcome within a full discovery sweep.
#[derive(Debug, Clone)]
pub struct ScannerScanReport {
    /// Scanner display name.
    pub scanner: String,

    /// Scan duration for this scanner.
    pub duration: Duration,

    /// Number of devices returned by this scanner.
    pub discovered: usize,

    /// Error message if this scanner failed.
    pub error: Option<String>,
}

/// Incremental discovery progress emitted as each scanner completes.
#[derive(Debug, Clone, Default)]
pub struct DiscoveryProgress {
    /// Devices seen for the first time in this scan step.
    pub new_devices: Vec<DeviceId>,

    /// Previously tracked devices observed again in this scan step.
    pub reappeared_devices: Vec<DeviceId>,
}

// ── DiscoveryOrchestrator ────────────────────────────────────────────────

type DiscoveryFuture = Pin<Box<dyn Future<Output = Result<Vec<DiscoveredDevice>>> + Send>>;

struct DiscoverySource {
    name: String,
    future: DiscoveryFuture,
}

/// Coordinates parallel device discovery across all registered driver sources.
///
/// Each instance owns one discovery batch and is consumed by
/// [`full_scan`](Self::full_scan). Startup, hot-plug, and on-demand callers
/// construct a fresh batch against the shared registry.
///
/// # Deduplication
///
/// The same physical device may be reported by multiple scanners through
/// different probe paths. The orchestrator deduplicates using
/// [`DeviceFingerprint`], keeping the richest metadata.
pub struct DiscoveryOrchestrator {
    sources: Vec<DiscoverySource>,

    /// Shared device registry.
    registry: DeviceRegistry,
}

impl DiscoveryOrchestrator {
    /// Create a new orchestrator with the given registry.
    ///
    /// Sources are added via [`add_source`](Self::add_source) before
    /// calling [`full_scan`](Self::full_scan).
    #[must_use]
    pub fn new(registry: DeviceRegistry) -> Self {
        Self {
            sources: Vec::new(),
            registry,
        }
    }

    /// Register one driver-owned discovery future.
    pub fn add_source<F, E>(&mut self, name: impl Into<String>, future: F)
    where
        F: Future<Output = Result<Vec<DiscoveredDevice>, E>> + Send + 'static,
        E: Into<anyhow::Error> + Send + 'static,
    {
        let name = name.into();
        info!(source = %name, "registered discovery source");
        self.sources.push(DiscoverySource {
            name,
            future: Box::pin(async move { future.await.map_err(Into::into) }),
        });
    }

    /// Number of registered discovery sources.
    #[must_use]
    pub fn source_count(&self) -> usize {
        self.sources.len()
    }

    /// Run this discovery batch across all registered sources.
    ///
    /// All scanners execute concurrently. Results are collected,
    /// deduplicated by fingerprint, and merged into the device registry.
    pub async fn full_scan(self) -> DiscoveryReport {
        self.full_scan_with_progress(|_| std::future::ready(()))
            .await
    }

    /// Run a full parallel scan and notify the caller as each scanner finishes.
    ///
    /// This allows higher layers to start device lifecycle work immediately
    /// instead of waiting for the entire discovery sweep to complete.
    #[expect(clippy::too_many_lines)]
    pub async fn full_scan_with_progress<F, Fut>(mut self, mut on_progress: F) -> DiscoveryReport
    where
        F: FnMut(DiscoveryProgress) -> Fut,
        Fut: Future<Output = ()>,
    {
        let scan_start = Instant::now();
        let known_before = self.registry.fingerprint_snapshot().await;
        // Diff by device id, not fingerprint text: a claimed device that
        // re-attached under a new fingerprint resolves to its existing
        // identity, and a fingerprint diff would call it new and vanished
        // at once.
        let known_ids_before: HashSet<DeviceId> = known_before.values().copied().collect();

        let sources = std::mem::take(&mut self.sources);
        let mut scan_tasks = JoinSet::new();
        for (index, source) in sources.into_iter().enumerate() {
            scan_tasks.spawn(async move {
                let started = Instant::now();
                let result = source.future.await;
                let elapsed = started.elapsed();
                (index, source.name, elapsed, result)
            });
        }

        let mut scanner_reports = Vec::new();
        let mut aggregated: HashMap<DeviceFingerprint, DiscoveredDevice> = HashMap::new();
        let mut new_devices = Vec::new();
        let mut reappeared_devices = Vec::new();
        let mut seen_ids = HashSet::new();

        while let Some(task) = scan_tasks.join_next().await {
            match task {
                Ok((index, scanner_name, elapsed, result)) => {
                    match result {
                        Ok(devices) => {
                            let discovered = devices.len();
                            info!(scanner = %scanner_name, count = devices.len(), "Scan complete");
                            scanner_reports.push((
                                index,
                                ScannerScanReport {
                                    scanner: scanner_name,
                                    duration: elapsed,
                                    discovered,
                                    error: None,
                                },
                            ));

                            let mut progress = DiscoveryProgress::default();
                            for device in devices {
                                let fingerprint = device.fingerprint.clone();

                                // Two units with a duplicated serial or MAC
                                // usually share a fingerprint, so this merge
                                // is the last place both observations exist.
                                // Capture the proof before dedup erases it.
                                let mut same_key_collision = None;
                                let merged = if let Some(existing) =
                                    aggregated.get_mut(&fingerprint)
                                {
                                    if let (Some(held), Some(incoming)) =
                                        (existing.claim.as_ref(), device.claim.as_ref())
                                        && held.key() == incoming.key()
                                        && held
                                            .evidence()
                                            .proves_distinct_from(&incoming.evidence())
                                    {
                                        same_key_collision = Some((held.clone(), incoming.clone()));
                                    }
                                    Self::merge_discovered(existing, &device);
                                    existing.clone()
                                } else {
                                    aggregated.insert(fingerprint.clone(), device);
                                    aggregated
                                        .get(&fingerprint)
                                        .cloned()
                                        .expect("inserted discovery entry should exist")
                                };

                                let id = self.registry.add_discovered(merged).await;
                                if let Some((held, incoming)) = same_key_collision {
                                    self.registry
                                        .report_portable_key_collision(
                                            id,
                                            fingerprint.clone(),
                                            held,
                                            incoming,
                                        )
                                        .await;
                                }

                                if seen_ids.insert(id) {
                                    if known_ids_before.contains(&id) {
                                        reappeared_devices.push(id);
                                        progress.reappeared_devices.push(id);
                                    } else {
                                        new_devices.push(id);
                                        progress.new_devices.push(id);
                                    }
                                }
                            }

                            if !(progress.new_devices.is_empty()
                                && progress.reappeared_devices.is_empty())
                            {
                                on_progress(progress).await;
                            }
                        }
                        Err(error) => {
                            warn!(scanner = %scanner_name, error = %error, "Scan failed");
                            scanner_reports.push((
                                index,
                                ScannerScanReport {
                                    scanner: scanner_name,
                                    duration: elapsed,
                                    discovered: 0,
                                    error: Some(error.to_string()),
                                },
                            ));
                        }
                    }
                }
                Err(join_error) => {
                    warn!(
                        error = %join_error,
                        "Scanner task failed before returning results"
                    );
                    scanner_reports.push((
                        usize::MAX,
                        ScannerScanReport {
                            scanner: "unknown".to_owned(),
                            duration: Duration::ZERO,
                            discovered: 0,
                            error: Some(format!("scanner task join failed: {join_error}")),
                        },
                    ));
                }
            }
        }
        scanner_reports.sort_by_key(|(index, _)| *index);

        let mut vanished_devices = known_ids_before
            .into_iter()
            .filter(|id| !seen_ids.contains(id))
            .collect::<Vec<_>>();
        vanished_devices.sort_by_key(DeviceId::as_uuid);

        let total_known = self.registry.len().await;
        let scan_duration = scan_start.elapsed();

        info!(
            new = new_devices.len(),
            reappeared = reappeared_devices.len(),
            vanished = vanished_devices.len(),
            total = total_known,
            duration_ms = scan_duration.as_millis(),
            "Discovery sweep complete"
        );

        DiscoveryReport {
            new_devices,
            reappeared_devices,
            vanished_devices,
            scanner_reports: scanner_reports
                .into_iter()
                .map(|(_, report)| report)
                .collect(),
            total_known,
            scan_duration,
        }
    }

    fn merge_discovered(existing: &mut DiscoveredDevice, incoming: &DiscoveredDevice) {
        existing.connect_behavior = existing.connect_behavior.merge(incoming.connect_behavior);

        if existing.claim.is_none() {
            existing.claim.clone_from(&incoming.claim);
        }

        for (key, value) in &incoming.metadata {
            existing
                .metadata
                .entry(key.clone())
                .or_insert_with(|| value.clone());
        }

        if existing.info.name.is_empty() && !incoming.info.name.is_empty() {
            existing.info.name.clone_from(&incoming.info.name);
        }

        if existing.info.vendor.is_empty() && !incoming.info.vendor.is_empty() {
            existing.info.vendor.clone_from(&incoming.info.vendor);
        }

        if existing.info.firmware_version.is_none() && incoming.info.firmware_version.is_some() {
            existing
                .info
                .firmware_version
                .clone_from(&incoming.info.firmware_version);
        }

        if existing.info.segments.is_empty() && !incoming.info.segments.is_empty() {
            existing.info.segments.clone_from(&incoming.info.segments);
        }

        if existing.info.capabilities.led_count == 0 && incoming.info.capabilities.led_count > 0 {
            existing.info.capabilities = incoming.info.capabilities;
        } else {
            existing.info.capabilities.led_count = existing
                .info
                .capabilities
                .led_count
                .max(incoming.info.capabilities.led_count);
            existing.info.capabilities.max_fps = existing
                .info
                .capabilities
                .max_fps
                .max(incoming.info.capabilities.max_fps);
            existing.info.capabilities.supports_direct |=
                incoming.info.capabilities.supports_direct;
            existing.info.capabilities.supports_brightness |=
                incoming.info.capabilities.supports_brightness;
        }
    }
}
