//! Discovery orchestrator — parallel scanner coordination and deduplication.
//!
//! The [`DiscoveryOrchestrator`] runs all registered transport scanners
//! concurrently, deduplicates their results, diffs against the device
//! registry, and reports what changed.

use std::collections::{HashMap, HashSet};
use std::time::{Duration, Instant};

use anyhow::Result;
use tracing::{info, warn};

use crate::types::device::{ConnectionType, DeviceFamily, DeviceFingerprint, DeviceId, DeviceInfo};

use super::registry::DeviceRegistry;

// ── TransportScanner ─────────────────────────────────────────────────────

/// A single-transport device scanner.
///
/// Implemented by transport-specific scanners (USB, mDNS, UDP broadcast,
/// `OpenRGB` gRPC). Each scanner probes one transport and returns all
/// currently reachable devices.
#[async_trait::async_trait]
pub trait TransportScanner: Send + Sync {
    /// Human-readable scanner name (for logging and diagnostics).
    fn name(&self) -> &str;

    /// Run a one-shot scan and return all currently reachable devices.
    ///
    /// Implementations should complete within the discovery time budget for
    /// their transport:
    ///
    /// | Transport | Target | Maximum |
    /// |-----------|--------|---------|
    /// | USB HID   | <100ms | 500ms   |
    /// | mDNS      | 3s     | 10s     |
    /// | UDP bcast | 3s     | 5s      |
    /// | `OpenRGB` | 1s     | 5s      |
    ///
    /// # Errors
    ///
    /// Returns an error if the transport is inaccessible or the scan
    /// encounters an unrecoverable failure.
    async fn scan(&mut self) -> Result<Vec<DiscoveredDevice>>;
}

// ── DiscoveredDevice ─────────────────────────────────────────────────────

/// Raw discovery result from a single scanner.
///
/// Contains enough information to construct or update a [`DeviceInfo`]
/// after enrichment and deduplication by the orchestrator.
#[derive(Debug, Clone)]
pub struct DiscoveredDevice {
    /// How this device connects to the host.
    pub connection_type: ConnectionType,

    /// Preliminary device name (from mDNS, USB descriptor, etc.).
    pub name: String,

    /// Device family, if identifiable from the transport layer.
    pub family: DeviceFamily,

    /// Stable identity fingerprint for deduplication.
    pub fingerprint: DeviceFingerprint,

    /// Pre-built device info ready for registry insertion.
    pub info: DeviceInfo,

    /// Additional metadata from the scanner (firmware version, LED count, etc.).
    pub metadata: HashMap<String, String>,
}

// ── DiscoveryReport ──────────────────────────────────────────────────────

/// Report generated by a full discovery sweep.
///
/// Summarizes what changed compared to the previous known device set.
#[derive(Debug)]
pub struct DiscoveryReport {
    /// Devices seen for the first time.
    pub new_devices: Vec<DeviceId>,

    /// Previously known devices that reappeared.
    pub reappeared_devices: Vec<DeviceId>,

    /// Previously known devices missing from this scan.
    pub vanished_devices: Vec<DeviceId>,

    /// Per-scanner timing and outcome diagnostics.
    pub scanner_reports: Vec<ScannerScanReport>,

    /// Total devices in the registry after this scan.
    pub total_known: usize,

    /// How long the full scan took.
    pub scan_duration: std::time::Duration,
}

/// One scanner's outcome within a full discovery sweep.
#[derive(Debug, Clone)]
pub struct ScannerScanReport {
    /// Scanner display name.
    pub scanner: String,

    /// Scan duration for this scanner.
    pub duration: Duration,

    /// Number of devices returned by this scanner.
    pub discovered: usize,

    /// Error message if this scanner failed.
    pub error: Option<String>,
}

// ── DiscoveryOrchestrator ────────────────────────────────────────────────

/// Coordinates parallel device discovery across all transport scanners.
///
/// At startup: runs a full scan across all transports simultaneously.
/// At runtime: listens for hot-plug hints and triggers targeted rescans.
/// On demand: `full_scan()` can be called from the REST API or CLI.
///
/// # Deduplication
///
/// The same physical device may be reported by multiple scanners (e.g., a
/// WLED device found via both mDNS and UDP broadcast). The orchestrator
/// deduplicates using [`DeviceFingerprint`], keeping the richest metadata.
pub struct DiscoveryOrchestrator {
    /// Registered scanners, one per transport.
    scanners: Vec<Box<dyn TransportScanner>>,

    /// Shared device registry.
    registry: DeviceRegistry,
}

impl DiscoveryOrchestrator {
    /// Create a new orchestrator with the given registry.
    ///
    /// Scanners are added via [`add_scanner`](Self::add_scanner) before
    /// calling [`full_scan`](Self::full_scan).
    #[must_use]
    pub fn new(registry: DeviceRegistry) -> Self {
        Self {
            scanners: Vec::new(),
            registry,
        }
    }

    /// Register a transport scanner.
    pub fn add_scanner(&mut self, scanner: Box<dyn TransportScanner>) {
        info!(scanner = scanner.name(), "Registered transport scanner");
        self.scanners.push(scanner);
    }

    /// Number of registered scanners.
    #[must_use]
    pub fn scanner_count(&self) -> usize {
        self.scanners.len()
    }

    /// Run a full parallel scan across all registered transports.
    ///
    /// All scanners execute concurrently. Results are collected,
    /// deduplicated by fingerprint, and merged into the device registry.
    #[expect(clippy::too_many_lines)]
    pub async fn full_scan(&mut self) -> DiscoveryReport {
        let scan_start = Instant::now();
        let known_before = self.registry.fingerprint_snapshot().await;

        // Move scanners out so each can be scanned on its own task.
        // We restore every scanner instance after awaiting task completion.
        let scanners = std::mem::take(&mut self.scanners);
        let mut scan_tasks = Vec::with_capacity(scanners.len());
        for mut scanner in scanners {
            scan_tasks.push(tokio::spawn(async move {
                let scanner_name = scanner.name().to_owned();
                let started = Instant::now();
                let result = scanner.scan().await;
                let elapsed = started.elapsed();
                (scanner, scanner_name, elapsed, result)
            }));
        }

        let mut all_discovered: Vec<DiscoveredDevice> = Vec::new();
        let mut restored_scanners = Vec::with_capacity(scan_tasks.len());
        let mut scanner_reports = Vec::with_capacity(scan_tasks.len());

        for task in scan_tasks {
            match task.await {
                Ok((scanner, scanner_name, elapsed, result)) => {
                    restored_scanners.push(scanner);
                    match result {
                        Ok(devices) => {
                            let discovered = devices.len();
                            info!(scanner = %scanner_name, count = devices.len(), "Scan complete");
                            scanner_reports.push(ScannerScanReport {
                                scanner: scanner_name,
                                duration: elapsed,
                                discovered,
                                error: None,
                            });
                            all_discovered.extend(devices);
                        }
                        Err(error) => {
                            warn!(scanner = %scanner_name, error = %error, "Scan failed");
                            scanner_reports.push(ScannerScanReport {
                                scanner: scanner_name,
                                duration: elapsed,
                                discovered: 0,
                                error: Some(error.to_string()),
                            });
                        }
                    }
                }
                Err(join_error) => {
                    warn!(
                        error = %join_error,
                        "Scanner task failed before returning results"
                    );
                    scanner_reports.push(ScannerScanReport {
                        scanner: "unknown".to_owned(),
                        duration: Duration::ZERO,
                        discovered: 0,
                        error: Some(format!("scanner task join failed: {join_error}")),
                    });
                }
            }
        }
        self.scanners = restored_scanners;

        // Deduplicate by fingerprint with metadata merging.
        let deduped = Self::deduplicate_devices(all_discovered);

        // Merge into registry
        let mut new_devices = Vec::new();
        let mut reappeared_devices = Vec::new();
        let mut seen_fingerprints = HashSet::with_capacity(deduped.len());

        for (fingerprint, discovered) in deduped {
            seen_fingerprints.insert(fingerprint.clone());
            let previously_known = self
                .registry
                .find_by_fingerprint(&discovered.fingerprint)
                .await;

            let id = self
                .registry
                .add_with_fingerprint(discovered.info, fingerprint)
                .await;

            if previously_known.is_some() {
                reappeared_devices.push(id);
            } else {
                new_devices.push(id);
            }
        }

        let mut vanished_devices = known_before
            .into_iter()
            .filter_map(|(fingerprint, id)| {
                (!seen_fingerprints.contains(&fingerprint)).then_some(id)
            })
            .collect::<Vec<_>>();
        vanished_devices.sort_by_key(DeviceId::as_uuid);

        let total_known = self.registry.len().await;
        let scan_duration = scan_start.elapsed();

        info!(
            new = new_devices.len(),
            reappeared = reappeared_devices.len(),
            vanished = vanished_devices.len(),
            total = total_known,
            duration_ms = scan_duration.as_millis(),
            "Discovery sweep complete"
        );

        DiscoveryReport {
            new_devices,
            reappeared_devices,
            vanished_devices,
            scanner_reports,
            total_known,
            scan_duration,
        }
    }

    /// Access the underlying device registry.
    #[must_use]
    pub fn registry(&self) -> &DeviceRegistry {
        &self.registry
    }

    fn deduplicate_devices(
        devices: Vec<DiscoveredDevice>,
    ) -> HashMap<DeviceFingerprint, DiscoveredDevice> {
        let mut deduped: HashMap<DeviceFingerprint, DiscoveredDevice> =
            HashMap::with_capacity(devices.len());

        for device in devices {
            let fingerprint = device.fingerprint.clone();
            deduped
                .entry(fingerprint)
                .and_modify(|existing| Self::merge_discovered(existing, &device))
                .or_insert(device);
        }

        deduped
    }

    fn merge_discovered(existing: &mut DiscoveredDevice, incoming: &DiscoveredDevice) {
        for (key, value) in &incoming.metadata {
            existing
                .metadata
                .entry(key.clone())
                .or_insert_with(|| value.clone());
        }

        if existing.name.is_empty() && !incoming.name.is_empty() {
            existing.name.clone_from(&incoming.name);
        }

        if existing.info.name.is_empty() && !incoming.info.name.is_empty() {
            existing.info.name.clone_from(&incoming.info.name);
        }

        if existing.info.vendor.is_empty() && !incoming.info.vendor.is_empty() {
            existing.info.vendor.clone_from(&incoming.info.vendor);
        }

        if existing.info.firmware_version.is_none() && incoming.info.firmware_version.is_some() {
            existing
                .info
                .firmware_version
                .clone_from(&incoming.info.firmware_version);
        }

        if existing.info.zones.is_empty() && !incoming.info.zones.is_empty() {
            existing.info.zones.clone_from(&incoming.info.zones);
        }

        if existing.info.capabilities.led_count == 0 && incoming.info.capabilities.led_count > 0 {
            existing.info.capabilities = incoming.info.capabilities;
        } else {
            existing.info.capabilities.led_count = existing
                .info
                .capabilities
                .led_count
                .max(incoming.info.capabilities.led_count);
            existing.info.capabilities.max_fps = existing
                .info
                .capabilities
                .max_fps
                .max(incoming.info.capabilities.max_fps);
            existing.info.capabilities.supports_direct |=
                incoming.info.capabilities.supports_direct;
            existing.info.capabilities.supports_brightness |=
                incoming.info.capabilities.supports_brightness;
        }
    }
}
