#!/usr/bin/env bun

import { chmodSync, cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const PACKAGE_ROOT = resolve(import.meta.dirname)
const DIST_DIR = join(PACKAGE_ROOT, 'dist')
const BIN_FILE = join(PACKAGE_ROOT, 'bin', 'hypercolor.js')
const TEMPLATES_DIR = join(PACKAGE_ROOT, 'templates')
const CREATE_EFFECT_TEMPLATES_DIR = join(PACKAGE_ROOT, '..', 'create-effect', 'templates')
const SHARED_PALETTES = join(PACKAGE_ROOT, '..', '..', 'shared', 'palettes.json')
const VENDORED_PALETTES = join(PACKAGE_ROOT, 'src', 'palette', 'palettes.gen.json')
const SHARED_COLOR_GLSL = join(PACKAGE_ROOT, '..', '..', 'shared', 'glsl', 'color.glsl')
const VENDORED_COLOR_GLSL = join(PACKAGE_ROOT, 'src', 'tooling', 'color-prelude.gen.ts')

/** The shared GLSL color prelude as a TypeScript string constant. */
function vendoredColorPrelude(): string {
    const source = readFileSync(SHARED_COLOR_GLSL, 'utf8')
    return [
        '// Generated by packages/core/build-package.ts from sdk/shared/glsl/color.glsl.',
        '// Do not edit. The npm tarball cannot reach sdk/shared, so the prelude is',
        '// vendored here; color-prelude-sync.test.ts asserts the copies match.',
        '',
        `export const COLOR_PRELUDE = ${JSON.stringify(source)}`,
        '',
    ].join('\n')
}

async function buildOrThrow(config: Bun.BuildConfig): Promise<void> {
    const result = await Bun.build(config)
    if (!result.success) {
        throw new AggregateError(
            result.logs.map((log) => new Error(log.message)),
            `Bun.build failed for ${config.entrypoints?.join(', ') ?? config.outfile ?? 'build output'}`,
        )
    }
}

async function main(): Promise<void> {
    rmSync(DIST_DIR, { force: true, recursive: true })
    rmSync(TEMPLATES_DIR, { force: true, recursive: true })
    mkdirSync(DIST_DIR, { recursive: true })
    cpSync(CREATE_EFFECT_TEMPLATES_DIR, TEMPLATES_DIR, { recursive: true })
    // The npm tarball cannot reach sdk/shared, so vendor the shared data
    // inside the package. The *-sync tests assert the copies match.
    cpSync(SHARED_PALETTES, VENDORED_PALETTES)
    writeFileSync(VENDORED_COLOR_GLSL, vendoredColorPrelude())

    await buildOrThrow({
        entrypoints: [join(PACKAGE_ROOT, 'src/index.ts')],
        format: 'esm',
        outdir: DIST_DIR,
        sourcemap: 'external',
        target: 'browser',
    })

    await buildOrThrow({
        entrypoints: [join(PACKAGE_ROOT, 'src/cli.ts'), join(PACKAGE_ROOT, 'src/tooling/metadata-worker.ts')],
        format: 'esm',
        naming: '[name].js',
        outdir: DIST_DIR,
        sourcemap: 'external',
        target: 'bun',
    })

    chmodSync(BIN_FILE, 0o755)
}

main().catch((error) => {
    console.error(error)
    process.exit(1)
})
