use super::frame_io::PublishFrameStats;
use super::pipeline_runtime::RenderSurfaceSnapshot;
use super::scene_snapshot::FrameSceneSnapshot;
use crate::performance::{CompositorBackendKind, FrameTimeline, LatestFrameMetrics};

pub(crate) struct ActiveFrameMetricsInput<'a> {
    pub(crate) scene_snapshot: &'a FrameSceneSnapshot,
    pub(crate) render_surfaces: &'a RenderSurfaceSnapshot,
    pub(crate) publish_stats: &'a PublishFrameStats,
    pub(crate) input_us: u32,
    pub(crate) producer_us: u32,
    pub(crate) producer_render_us: u32,
    pub(crate) producer_scene_compose_us: u32,
    pub(crate) composition_us: u32,
    pub(crate) producer_done_us: u32,
    pub(crate) composition_done_us: u32,
    pub(crate) render_us: u32,
    pub(crate) sample_us: u32,
    pub(crate) push_us: u32,
    pub(crate) postprocess_us: u32,
    pub(crate) total_us: u32,
    pub(crate) wake_late_us: u32,
    pub(crate) jitter_us: u32,
    pub(crate) overhead_us: u32,
    pub(crate) reused_inputs: bool,
    pub(crate) reused_canvas: bool,
    pub(crate) gpu_zone_sampling: bool,
    pub(crate) gpu_sample_deferred: bool,
    pub(crate) gpu_sample_retry_hit: bool,
    pub(crate) gpu_sample_queue_saturated: bool,
    pub(crate) gpu_sample_wait_blocked: bool,
    pub(crate) cpu_readback_skipped: bool,
    pub(crate) compositor_backend: CompositorBackendKind,
    pub(crate) output_errors: u32,
    pub(crate) logical_layer_count: u32,
    pub(crate) render_group_count: u32,
    pub(crate) scene_active: bool,
    pub(crate) scene_transition_active: bool,
    pub(crate) effect_retained: bool,
    pub(crate) screen_retained: bool,
    pub(crate) composition_bypassed: bool,
    pub(crate) scene_snapshot_done_us: u32,
    pub(crate) input_done_us: u32,
    pub(crate) sample_done_us: u32,
    pub(crate) output_done_us: u32,
    pub(crate) publish_done_us: u32,
}

pub(crate) struct ThrottleFrameMetricsInput<'a> {
    pub(crate) scene_snapshot: &'a FrameSceneSnapshot,
    pub(crate) render_surfaces: &'a RenderSurfaceSnapshot,
    pub(crate) publish_stats: &'a PublishFrameStats,
    pub(crate) sample_us: u32,
    pub(crate) push_us: u32,
    pub(crate) total_us: u32,
    pub(crate) overhead_us: u32,
    pub(crate) output_errors: u32,
    pub(crate) scene_snapshot_done_us: u32,
    pub(crate) sample_done_us: u32,
    pub(crate) output_done_us: u32,
    pub(crate) publish_done_us: u32,
}

pub(crate) fn build_active_frame_metrics(
    input: ActiveFrameMetricsInput<'_>,
) -> LatestFrameMetrics {
    let ActiveFrameMetricsInput {
        scene_snapshot,
        render_surfaces,
        publish_stats,
        input_us,
        producer_us,
        producer_render_us,
        producer_scene_compose_us,
        composition_us,
        producer_done_us,
        composition_done_us,
        render_us,
        sample_us,
        push_us,
        postprocess_us,
        total_us,
        wake_late_us,
        jitter_us,
        overhead_us,
        reused_inputs,
        reused_canvas,
        gpu_zone_sampling,
        gpu_sample_deferred,
        gpu_sample_retry_hit,
        gpu_sample_queue_saturated,
        gpu_sample_wait_blocked,
        cpu_readback_skipped,
        compositor_backend,
        output_errors,
        logical_layer_count,
        render_group_count,
        scene_active,
        scene_transition_active,
        effect_retained,
        screen_retained,
        composition_bypassed,
        scene_snapshot_done_us,
        input_done_us,
        sample_done_us,
        output_done_us,
        publish_done_us,
    } = input;
    LatestFrameMetrics {
        timestamp_ms: scene_snapshot.elapsed_ms,
        input_us,
        producer_us,
        producer_render_us,
        producer_scene_compose_us,
        composition_us,
        render_us,
        sample_us,
        push_us,
        postprocess_us,
        publish_us: publish_stats.elapsed_us,
        publish_frame_data_us: publish_stats.frame_data_us,
        publish_group_canvas_us: publish_stats.group_canvas_us,
        publish_preview_us: publish_stats.preview_us,
        publish_events_us: publish_stats.events_us,
        overhead_us,
        total_us,
        wake_late_us,
        jitter_us,
        reused_inputs,
        reused_canvas,
        retained_effect: effect_retained,
        retained_screen: screen_retained,
        composition_bypassed,
        gpu_zone_sampling,
        gpu_sample_deferred,
        gpu_sample_retry_hit,
        gpu_sample_queue_saturated,
        gpu_sample_wait_blocked,
        cpu_readback_skipped,
        compositor_backend,
        logical_layer_count,
        render_group_count,
        scene_active,
        scene_transition_active,
        render_surface_slot_count: render_surfaces.slot_count,
        render_surface_free_slots: render_surfaces.free_slots,
        render_surface_published_slots: render_surfaces.published_slots,
        render_surface_dequeued_slots: render_surfaces.dequeued_slots,
        scene_pool_saturation_reallocs: render_surfaces.scene_pool_saturation_reallocs,
        direct_pool_saturation_reallocs: render_surfaces.direct_pool_saturation_reallocs,
        scene_pool_grown_slots: render_surfaces.scene_pool_grown_slots,
        direct_pool_grown_slots: render_surfaces.direct_pool_grown_slots,
        canvas_receiver_count: render_surfaces.canvas_receivers,
        full_frame_copy_count: publish_stats.full_frame_copy_count,
        full_frame_copy_bytes: publish_stats.full_frame_copy_bytes,
        output_errors,
        timeline: build_frame_timeline(
            scene_snapshot,
            scene_snapshot_done_us,
            input_done_us,
            input_done_us.saturating_add(producer_done_us),
            input_done_us.saturating_add(composition_done_us),
            sample_done_us,
            output_done_us,
            publish_done_us,
            total_us,
        ),
    }
}

pub(crate) fn build_throttle_frame_metrics(
    input: ThrottleFrameMetricsInput<'_>,
) -> LatestFrameMetrics {
    let ThrottleFrameMetricsInput {
        scene_snapshot,
        render_surfaces,
        publish_stats,
        sample_us,
        push_us,
        total_us,
        overhead_us,
        output_errors,
        scene_snapshot_done_us,
        sample_done_us,
        output_done_us,
        publish_done_us,
    } = input;
    LatestFrameMetrics {
        timestamp_ms: scene_snapshot.elapsed_ms,
        input_us: 0,
        producer_us: 0,
        producer_render_us: 0,
        producer_scene_compose_us: 0,
        composition_us: 0,
        render_us: 0,
        sample_us,
        push_us,
        postprocess_us: 0,
        publish_us: publish_stats.elapsed_us,
        publish_frame_data_us: publish_stats.frame_data_us,
        publish_group_canvas_us: publish_stats.group_canvas_us,
        publish_preview_us: publish_stats.preview_us,
        publish_events_us: publish_stats.events_us,
        overhead_us,
        total_us,
        wake_late_us: 0,
        jitter_us: 0,
        reused_inputs: false,
        reused_canvas: false,
        retained_effect: false,
        retained_screen: false,
        composition_bypassed: false,
        gpu_zone_sampling: false,
        gpu_sample_deferred: false,
        gpu_sample_retry_hit: false,
        gpu_sample_queue_saturated: false,
        gpu_sample_wait_blocked: false,
        cpu_readback_skipped: false,
        compositor_backend: CompositorBackendKind::Cpu,
        logical_layer_count: 0,
        render_group_count: scene_snapshot.scene_runtime.active_render_group_count(),
        scene_active: scene_snapshot.scene_runtime.active_scene_id.is_some(),
        scene_transition_active: scene_snapshot.scene_runtime.active_transition.is_some(),
        render_surface_slot_count: render_surfaces.slot_count,
        render_surface_free_slots: render_surfaces.free_slots,
        render_surface_published_slots: render_surfaces.published_slots,
        render_surface_dequeued_slots: render_surfaces.dequeued_slots,
        scene_pool_saturation_reallocs: render_surfaces.scene_pool_saturation_reallocs,
        direct_pool_saturation_reallocs: render_surfaces.direct_pool_saturation_reallocs,
        scene_pool_grown_slots: render_surfaces.scene_pool_grown_slots,
        direct_pool_grown_slots: render_surfaces.direct_pool_grown_slots,
        canvas_receiver_count: render_surfaces.canvas_receivers,
        full_frame_copy_count: publish_stats.full_frame_copy_count,
        full_frame_copy_bytes: publish_stats.full_frame_copy_bytes,
        output_errors,
        timeline: build_frame_timeline(
            scene_snapshot,
            scene_snapshot_done_us,
            scene_snapshot_done_us,
            scene_snapshot_done_us,
            scene_snapshot_done_us,
            sample_done_us,
            output_done_us,
            publish_done_us,
            total_us,
        ),
    }
}

fn build_frame_timeline(
    scene_snapshot: &FrameSceneSnapshot,
    scene_snapshot_done_us: u32,
    input_done_us: u32,
    producer_done_us: u32,
    composition_done_us: u32,
    sample_done_us: u32,
    output_done_us: u32,
    publish_done_us: u32,
    frame_done_us: u32,
) -> FrameTimeline {
    FrameTimeline {
        frame_token: scene_snapshot.frame_token,
        budget_us: scene_snapshot.budget_us,
        scene_snapshot_done_us,
        input_done_us,
        producer_done_us,
        composition_done_us,
        sample_done_us,
        output_done_us,
        publish_done_us,
        frame_done_us,
    }
}
