import { effect } from '@hypercolor/sdk'
import shader from './fragment.glsl'

export default effect('Borealis', shader, {
    speed:          [1, 10, 5],
    intensity:      [0, 100, 82],
    warpStrength:   [0, 100, 62],
    starBrightness: [0, 100, 40],
    curtainHeight:  [20, 90, 55],
    saturation:     [60, 150, 118],
    contrast:       [70, 140, 104],
    banding:        [0, 100, 34],
    palette:        ['Cyberpunk', 'Fire', 'Ice', 'Northern Lights', 'Phosphor', 'SilkCircuit', 'Sunset', 'Vaporwave'],
}, {
    description: 'Aurora borealis — layered curtains of light with richer palette grading and tonal control',
    presets: [
        {
            name: 'Arctic Solstice',
            description: 'Midnight sun refracting through polar ice — slow, towering curtains in crystalline blues and greens',
            controls: {
                speed: 2,
                intensity: 90,
                warpStrength: 45,
                starBrightness: 75,
                curtainHeight: 85,
                saturation: 135,
                contrast: 120,
                banding: 18,
                palette: 'Ice',
            },
        },
        {
            name: 'Magnetic Storm',
            description: 'A solar wind eruption tears the sky open — violent ribbons whip and shatter at impossible speed',
            controls: {
                speed: 9,
                intensity: 100,
                warpStrength: 95,
                starBrightness: 20,
                curtainHeight: 70,
                saturation: 145,
                contrast: 138,
                banding: 85,
                palette: 'Cyberpunk',
            },
        },
        {
            name: 'Phosphor Dreams',
            description: 'Bioluminescent plankton drifting through the thermosphere — ghostly green veils pulse in slow motion',
            controls: {
                speed: 3,
                intensity: 65,
                warpStrength: 30,
                starBrightness: 55,
                curtainHeight: 40,
                saturation: 80,
                contrast: 85,
                banding: 50,
                palette: 'Phosphor',
            },
        },
        {
            name: 'Ritual Veil',
            description: 'Ancient light ceremony above a volcanic plateau — deep magentas and ambers weave through sacred geometry',
            controls: {
                speed: 4,
                intensity: 78,
                warpStrength: 80,
                starBrightness: 10,
                curtainHeight: 60,
                saturation: 125,
                contrast: 130,
                banding: 70,
                palette: 'Sunset',
            },
        },
        {
            name: 'Silicon Vaporwave',
            description: 'A retro-future skyline hums with neon — synthetic aurora over a digital ocean at dusk',
            controls: {
                speed: 6,
                intensity: 88,
                warpStrength: 72,
                starBrightness: 35,
                curtainHeight: 50,
                saturation: 148,
                contrast: 110,
                banding: 42,
                palette: 'Vaporwave',
            },
        },
    ],
})
