schema_version = 1
id = "corsair-9000d-io-strip"
name = "Corsair LINK 9000D IO - 18 LED"
category = "strip"
origin = "built_in"
description = "Corsair LINK 9000D IO - 18 LED"
vendor = "Corsair"
compatible_slots = []
tags = [
    "strip",
]
led_mapping = [
    17,
    16,
    15,
    14,
    13,
    12,
    11,
    10,
    9,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
]

[default_size]
width = 0.23999999463558197
height = 0.07999999821186066

[topology]
type = "matrix"
width = 9
height = 2
serpentine = false
start_corner = "top_left"
