schema_version = 1
id = "corsair-xd5-reservior"
name = "XD5 Reservior - 10 Led"
category = "water_block"
origin = "built_in"
description = "XD5 Reservior - 10 Led"
vendor = "Corsair"
compatible_slots = []
tags = [
    "water-block",
]
led_names = [
    "Led 1",
    "Led 2",
    "Led 3",
    "Led 5",
    "Led 7",
    "Led 10",
    "Led 9",
    "Led 8",
    "Led 6",
    "Led 4",
]

[default_size]
width = 0.23999999463558197
height = 0.23999999463558197

[topology]
type = "perimeter_loop"
top = 3
right = 3
bottom = 2
left = 2
start_corner = "top_left"
direction = "clockwise"
