"""Generate the vendored OpenAPI client."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import IO

PYTHON_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PYTHON_ROOT.parent
GENERATED_ROOT = PYTHON_ROOT / "src" / "hypercolor" / "_generated"


def main() -> None:
    args = parse_args()

    with tempfile.TemporaryDirectory(prefix="hypercolor-openapi-") as temp_dir_raw:
        temp_dir = Path(temp_dir_raw)
        spec_path = Path(args.spec) if args.spec else export_openapi(temp_dir)
        validate_json(spec_path)
        spec_path = prepare_generator_spec(spec_path, temp_dir)
        output_path = temp_dir / "client"
        run(
            [
                "uv",
                "run",
                "--group",
                "generate",
                "openapi-python-client",
                "generate",
                "--path",
                str(spec_path),
                "--meta",
                "none",
                "--output-path",
                str(output_path),
                "--overwrite",
                "--fail-on-warning",
            ],
            cwd=PYTHON_ROOT,
        )
        write_generated_marker(output_path)
        if args.check:
            ensure_generated_matches(output_path)
        else:
            replace_generated(output_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--spec",
        type=Path,
        help="Use an existing OpenAPI JSON document instead of exporting one with Cargo.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files differ from the checked-in copy.",
    )
    return parser.parse_args()


def export_openapi(temp_dir: Path) -> Path:
    spec_path = temp_dir / "openapi.json"
    with spec_path.open("w", encoding="utf-8") as spec_file:
        run(
            ["cargo", "run", "-p", "hypercolor-daemon", "--bin", "hypercolor-openapi", "--quiet"],
            cwd=REPO_ROOT,
            stdout=spec_file,
        )
    return spec_path


def validate_json(path: Path) -> None:
    with path.open(encoding="utf-8") as spec_file:
        json.load(spec_file)


def prepare_generator_spec(path: Path, temp_dir: Path) -> Path:
    with path.open(encoding="utf-8") as spec_file:
        spec = json.load(spec_file)

    schemas = spec.get("components", {}).get("schemas", {})
    for name in (
        "ControlApplyError",
        "ControlOwner",
        "ControlSurfaceEvent",
        "ControlSurfaceScope",
    ):
        schema = schemas.get(name)
        if isinstance(schema, dict):
            schemas[name] = {
                "type": "object",
                "description": schema.get("description", f"{name} payload"),
            }

    generator_spec = temp_dir / "openapi-python-client.json"
    generator_spec.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    return generator_spec


def replace_generated(source: Path) -> None:
    if GENERATED_ROOT.exists():
        shutil.rmtree(GENERATED_ROOT)
    ignore = shutil.ignore_patterns(".ruff_cache", "__pycache__", "*.pyc")
    shutil.copytree(source, GENERATED_ROOT, ignore=ignore)


def write_generated_marker(root: Path) -> None:
    (root / "GENERATED.md").write_text(
        "\n".join(
            [
                "# Generated Hypercolor OpenAPI Client",
                "",
                "This private package is generated by `python/scripts/generate_openapi_client.py`.",
                "Do not edit these files by hand.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def ensure_generated_matches(source: Path) -> None:
    expected_files = relative_files(source)
    actual_files = relative_files(GENERATED_ROOT)
    missing = expected_files - actual_files
    extra = actual_files - expected_files
    changed = {
        path
        for path in expected_files & actual_files
        if (source / path).read_bytes() != (GENERATED_ROOT / path).read_bytes()
    }
    if missing or extra or changed:
        for label, paths in (("missing", missing), ("extra", extra), ("changed", changed)):
            for path in sorted(paths)[:20]:
                print(f"{label}: {path}", file=sys.stderr)
        raise SystemExit("generated OpenAPI client is out of date")


def relative_files(root: Path) -> set[Path]:
    if not root.exists():
        return set()
    return {
        path.relative_to(root)
        for path in root.rglob("*")
        if path.is_file()
        and ".ruff_cache" not in path.parts
        and "__pycache__" not in path.parts
        and path.suffix != ".pyc"
    }


def run(
    command: list[str],
    *,
    cwd: Path,
    stdout: IO[str] | None = None,
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.setdefault("CARGO_TARGET_DIR", str(Path.home() / ".cache" / "hypercolor" / "target"))
    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        stdout=stdout,
        text=True,
        check=True,
    )


if __name__ == "__main__":
    main()
