#!/usr/bin/env bun
/**
 * OpenRGB detector USB id map generator.
 *
 * Reads the udev rules an unmodified OpenRGB binary generates and writes
 * crates/hypercolor-openrgb-host/data/detector_usb_ids.toml: one entry per
 * OpenRGB detector name, listing the USB vendor:product ids that detector
 * claims. The managed detector partition (Spec 81 §3.1) uses the map to
 * disable only the detectors whose devices a native driver can claim.
 *
 * Starting with OpenRGB 1.0 the rules are generated by the binary itself,
 * one comment-headed section per detector, the header being the detector
 * name exactly as `Detectors.detectors` in OpenRGB.json spells it. Reading
 * that output is black-box provenance (Spec 68): no OpenRGB source is read.
 *
 * Usage:
 *   openrgb --print-udev-rules > /tmp/60-openrgb.rules
 *   bun scripts/gen-openrgb-detector-ids.ts /tmp/60-openrgb.rules
 *
 * A distro package's installed copy (/usr/lib/udev/rules.d/60-openrgb.rules)
 * is the same generated artifact and works as input too.
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(SCRIPT_DIR, '..')
const OUTPUT = join(REPO_ROOT, 'crates', 'hypercolor-openrgb-host', 'data', 'detector_usb_ids.toml')

const SECTION_RULE = /^#-{8,}#?\s*$/
const SECTION_NAME = /^# {2}(.+?)(?:\s+#)?\s*$/
const VENDOR = /ATTRS?\{idVendor\}=="([0-9a-fA-F]{4})"/
const PRODUCT = /ATTRS?\{idProduct\}=="([0-9a-fA-F]{4})"/
const GENERATED_BY = /^Generated by OpenRGB (.+)$/
const GIT_COMMIT = /^Git commit:\s*(.*)$/

interface ParsedRules {
    version: string
    commit: string
    detectors: Map<string, Set<string>>
}

function parseRules(text: string): ParsedRules {
    let version = ''
    let commit = ''
    let current: string | undefined
    let previous = ''
    const detectors = new Map<string, Set<string>>()

    for (const raw of text.split(/\r?\n/)) {
        const line = raw.trimEnd()
        if (line.startsWith('#')) {
            const text = SECTION_NAME.exec(line)?.[1]
            if (text !== undefined) {
                version = GENERATED_BY.exec(text)?.[1]?.trim() ?? version
                const commitMatch = GIT_COMMIT.exec(text)
                if (commitMatch) commit = commitMatch[1]?.trim() ?? ''
                // Only the line right under a rule opens a detector section.
                if (SECTION_RULE.test(previous)) current = text
            }
            previous = line
            continue
        }
        previous = line
        const vendor = VENDOR.exec(line)?.[1]
        if (current === undefined || vendor === undefined) continue
        // A rule without a product id grants the whole vendor: the detector
        // may claim any product from it, so record a vendor wildcard.
        const product = PRODUCT.exec(line)?.[1] ?? '*'
        const ids = detectors.get(current) ?? new Set<string>()
        ids.add(`${vendor.toLowerCase()}:${product.toLowerCase()}`)
        detectors.set(current, ids)
    }

    if (version === '') {
        throw new Error('input has no "Generated by OpenRGB <version>" header; is it OpenRGB udev output?')
    }
    return { version, commit, detectors }
}

function sortIds(ids: Set<string>): string[] {
    // A vendor wildcard subsumes every exact id from the same vendor.
    const wildVendors = new Set([...ids].filter((id) => id.endsWith(':*')).map((id) => id.slice(0, 4)))
    return [...ids]
        .filter((id) => id.endsWith(':*') || !wildVendors.has(id.slice(0, 4)))
        .sort()
}

function render(parsed: ParsedRules, sha256: string): string {
    const names = [...parsed.detectors.keys()].sort()
    const wildcards = names.filter((name) => sortIds(parsed.detectors.get(name)!).some((id) => id.endsWith(':*')))
    const lines = [
        '# OpenRGB detector name -> USB vendor:product ids that detector claims.',
        '#',
        '# GENERATED by scripts/gen-openrgb-detector-ids.ts; do not hand-edit.',
        '# Regenerate from the udev rules a new OpenRGB release prints:',
        '#   openrgb --print-udev-rules > /tmp/60-openrgb.rules',
        '#   bun scripts/gen-openrgb-detector-ids.ts /tmp/60-openrgb.rules',
        '#',
        '# Provenance: black-box output of an unmodified OpenRGB binary (Spec 68).',
        '# OpenRGB generates its udev rules from its own detector registry, one',
        '# section per detector headed by the detector name exactly as the',
        '# Detectors.detectors map in OpenRGB.json spells it. No OpenRGB source',
        '# was read to build this file.',
        '#',
        '# The managed detector partition (Spec 81 §3.1) disables a detector when',
        '# any id it lists is one an enabled native driver can claim. `vvvv:*`',
        '# means the detector matches every product from that vendor (OpenRGB',
        '# probes those by HID usage, not product id). Detectors with no USB id at',
        '# all (SMBus RAM and mainboard controllers, laptop platform interfaces)',
        '# are absent and stay on the conservative name-prefix rule.',
        '',
        '[source]',
        `openrgb_version = ${JSON.stringify(parsed.version)}`,
        `git_commit = ${JSON.stringify(parsed.commit)}`,
        'artifact = "openrgb --print-udev-rules (60-openrgb.rules)"',
        `sha256 = ${JSON.stringify(sha256)}`,
        `detector_count = ${names.length}`,
        `vendor_wildcard_detectors = [${wildcards.map((name) => JSON.stringify(name)).join(', ')}]`,
        '',
        '[detectors]',
    ]
    for (const name of names) {
        const ids = sortIds(parsed.detectors.get(name)!)
        lines.push(`${JSON.stringify(name)} = [${ids.map((id) => JSON.stringify(id)).join(', ')}]`)
    }
    return `${lines.join('\n')}\n`
}

function main(): void {
    const input = process.argv[2]
    if (input === undefined || input.startsWith('-')) {
        console.error('usage: bun scripts/gen-openrgb-detector-ids.ts <60-openrgb.rules>')
        process.exit(2)
    }
    const bytes = readFileSync(input)
    const sha256 = createHash('sha256').update(bytes).digest('hex')
    const parsed = parseRules(bytes.toString('utf8'))
    writeFileSync(OUTPUT, render(parsed, sha256))
    let idCount = 0
    for (const ids of parsed.detectors.values()) idCount += ids.size
    console.log(
        `wrote ${OUTPUT}: ${parsed.detectors.size} detectors, ${idCount} ids, OpenRGB ${parsed.version}`,
    )
}

main()
