//! Tray icon generation and state mapping.
//!
//! Pre-baked PNGs of the canonical trinity mark, one per state. The PNGs
//! are generated by `assets/brand/build.py` from the master brand and
//! committed under `crates/hypercolor-app/icons/tray/`. We decode them at
//! runtime (cold path — only fires on state changes) and hand the RGBA
//! buffer to Tauri.

use std::io::Cursor;

use image::ImageReader;
use tauri::image::Image;

use crate::state::AppState;

/// Icon size in pixels. Pre-baked PNGs must match this.
const ICON_SIZE: u32 = 32;

const ICON_ACTIVE: &[u8] = include_bytes!("../../icons/tray/tray-active-32.png");
const ICON_PAUSED: &[u8] = include_bytes!("../../icons/tray/tray-paused-32.png");
const ICON_DISCONNECTED: &[u8] =
    include_bytes!("../../icons/tray/tray-disconnected-32.png");
const ICON_ERROR: &[u8] = include_bytes!("../../icons/tray/tray-error-32.png");

/// Visual states for the tray icon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconState {
    /// Daemon running with live output.
    Active,
    /// Daemon running with rendering paused.
    Paused,
    /// Daemon not reachable.
    Disconnected,
    /// Daemon error state.
    Error,
}

/// Pick the tray icon state from the current app state.
///
/// Considers only the app's view of the daemon. Use
/// [`icon_state_for_with_supervisor`] when the supervisor's permanent-
/// failure latch is also available — that's the path that surfaces
/// `IconState::Error` (watchdog gave up after the rapid-restart cap).
#[must_use]
pub fn icon_state_for(state: &AppState) -> IconState {
    icon_state_for_with_supervisor(state, false)
}

/// Pick the tray icon state with supervisor visibility.
///
/// `supervisor_failed` is sourced from
/// `SupervisorState::permanent_failure()` — when true, the tray
/// surfaces the red Error icon regardless of whether the daemon is
/// momentarily reachable, because the supervisor has stopped trying
/// to keep it alive.
#[must_use]
pub fn icon_state_for_with_supervisor(state: &AppState, supervisor_failed: bool) -> IconState {
    if supervisor_failed {
        IconState::Error
    } else if !state.connected {
        IconState::Disconnected
    } else if state.paused {
        IconState::Paused
    } else {
        IconState::Active
    }
}

/// Build a Tauri image for the given tray icon state.
#[must_use]
pub fn build_icon(state: IconState) -> Image<'static> {
    Image::new_owned(render_icon(state), ICON_SIZE, ICON_SIZE)
}

/// Decode the pre-baked PNG for the given state into an RGBA pixel buffer.
fn render_icon(state: IconState) -> Vec<u8> {
    let png_bytes: &[u8] = match state {
        IconState::Active => ICON_ACTIVE,
        IconState::Paused => ICON_PAUSED,
        IconState::Disconnected => ICON_DISCONNECTED,
        IconState::Error => ICON_ERROR,
    };

    let img = ImageReader::with_format(Cursor::new(png_bytes), image::ImageFormat::Png)
        .decode()
        .expect("compiled-in PNG decodes")
        .to_rgba8();
    debug_assert_eq!(img.width(), ICON_SIZE);
    debug_assert_eq!(img.height(), ICON_SIZE);
    img.into_raw()
}

#[cfg(test)]
#[allow(clippy::as_conversions)]
mod tests {
    use super::*;

    const PIXEL_COUNT: usize = (ICON_SIZE as usize) * (ICON_SIZE as usize) * 4;

    #[test]
    fn render_icon_produces_correct_size() {
        for state in [
            IconState::Active,
            IconState::Paused,
            IconState::Disconnected,
            IconState::Error,
        ] {
            let rgba = render_icon(state);
            assert_eq!(rgba.len(), PIXEL_COUNT);
        }
    }

    #[test]
    fn states_render_distinct_icons() {
        let active = render_icon(IconState::Active);
        let paused = render_icon(IconState::Paused);
        let disconnected = render_icon(IconState::Disconnected);
        let error = render_icon(IconState::Error);
        assert_ne!(active, paused);
        assert_ne!(active, disconnected);
        assert_ne!(active, error);
        assert_ne!(paused, error);
    }
}
